server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name localhost;

    http2 on;

    ssl_certificate     /etc/ssl/localhost.crt;
    ssl_certificate_key /etc/ssl/localhost.key;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;

    root /var/www/html;
    index index.html;
}
